services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ebbl_app
    restart: unless-stopped
    networks:
      - ebbl_network
    ports:
      - "80:80"
    environment:
      - APP_ENV=production
    volumes:
      - .env:/var/www/html/.env:rw
      # If you need to persist storage, uncomment below
      # - ./storage:/var/www/html/storage
    depends_on:
      - mysql

  mysql:
    image: percona:8.0
    container_name: ebbl_mysql
    restart: unless-stopped
    networks:
      - ebbl_network
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ebbm
      MYSQL_USER: ebbm_user
      MYSQL_PASSWORD: ebbm_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

networks:
  ebbl_network:
    driver: bridge

volumes:
  mysql_data: