services:
  # PHP-FPM Service
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ebbm_php
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./docker/php/php-fpm-pool.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=ebbm_local
      - DB_USERNAME=ebbm_user
      - DB_PASSWORD=ebbm_password
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    networks:
      - ebbm_network

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: ebbm_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - ebbm_network

  # Percona MySQL Service
  mysql:
    image: percona:8.0
    container_name: ebbm_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ebbm_local
      MYSQL_USER: ebbm_user
      MYSQL_PASSWORD: ebbm_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/logs:/var/log/mysql
    networks:
      - ebbm_network

  # Redis Service for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: ebbm_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - ebbm_network

  # Node.js for Vite development server
  node:
    image: node:18-alpine
    container_name: ebbm_node
    restart: unless-stopped
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    networks:
      - ebbm_network

  # Development tools (optional, use with --profile dev)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ebbm_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root_password
    depends_on:
      - mysql
    networks:
      - ebbm_network
    profiles:
      - dev

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: ebbm_redis_commander
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - ebbm_network
    profiles:
      - dev

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  ebbm_network:
    driver: bridge